services:
  postgres:
    image: postgres:16.4-alpine
    container_name: voicecare_postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5444:5432"
    volumes:
      - voicecare_postgres:/var/lib/postgresql/data

volumes:
  voicecare_postgres:
